spring:
    application:
        name: dataBude
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/databude
        username: finn
        password: Finn2005
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                orm:
                    jdbc:
                        bind: TRACE

config:
    emptyUserProfileUrl: https://i.imgur.com/tdi3NGa.png